### ISSUE TITLE
First created question doesn't accept the correct answer (Debian/Chrome)

### ISSUE THREAD

**Issue by Vaakapallo** [rage/parqu#1]
It seems like for some users the first generated question says that all the options are wrong. Happens at least on Chrome running on Debian.

Choosing "New exercise" fixes the problem.

![firstanswerwrong](https://cloud.githubusercontent.com/assets/2619272/5987718/8f48a1e0-a943-11e4-95a4-4833ad7c3d7f.jpg)

**Comment by Vaakapallo** [comment]
Might be that the server went to sleep between generating the questions and receiving the answers.

Or that the material was open for so long before answering that the server deleted them after 24 hours, expecting them to never be answered.

**Comment by Vaakapallo** [comment]
Can be fixed by generating the questions when you click the name of the question, not when the page loads.

**Comment by jamo** [comment]
plz use https for tmc auth

**Comment by avihavai** [comment]
Auth is perhaps not relevant for this bug, the above log entry is a part of the MOOC-material <tm> :) -- digging into the MOOC-material to change it.

**Comment by jamo** [comment]
Yep not relevant for this bug though I weren't sure what would be the best place to report it :)

**Comment by avihavai** [comment]
All right, changed that part. No passwords were transmitted anyway though (and the username is being passed around :/).

**Comment by Vaakapallo** [comment]
Fixed in the JS library by generating questions when clicked, not on page load.
